// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlddGR16Xh8u95NEl-KX-qqyCTQtph2K8',
    appId: '1:195164235689:web:79784583d1721337c206b8',
    messagingSenderId: '195164235689',
    projectId: 'newworld-e5f58',
    authDomain: 'newworld-e5f58.firebaseapp.com',
    storageBucket: 'newworld-e5f58.firebasestorage.app',
    measurementId: 'G-H59BLV5RP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Had4W161FLMe1p5mWSYLaAuZMSNcP8M',
    appId: '1:195164235689:android:3a34b0718e616cbec206b8',
    messagingSenderId: '195164235689',
    projectId: 'newworld-e5f58',
    storageBucket: 'newworld-e5f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHTR7MRpKKD6CVwF2bAsjFuyYc_ry2s4',
    appId: '1:195164235689:ios:9ff26a5c2005e198c206b8',
    messagingSenderId: '195164235689',
    projectId: 'newworld-e5f58',
    storageBucket: 'newworld-e5f58.firebasestorage.app',
    iosBundleId: 'com.example.ticktokclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlddGR16Xh8u95NEl-KX-qqyCTQtph2K8',
    appId: '1:195164235689:web:79784583d1721337c206b8',
    messagingSenderId: '195164235689',
    projectId: 'newworld-e5f58',
    authDomain: 'newworld-e5f58.firebaseapp.com',
    storageBucket: 'newworld-e5f58.firebasestorage.app',
    measurementId: 'G-H59BLV5RP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArHTR7MRpKKD6CVwF2bAsjFuyYc_ry2s4',
    appId: '1:195164235689:ios:9ff26a5c2005e198c206b8',
    messagingSenderId: '195164235689',
    projectId: 'newworld-e5f58',
    storageBucket: 'newworld-e5f58.firebasestorage.app',
    iosBundleId: 'com.example.ticktokclone',
  );

}